blocked-words:
  - kontol
  - Kontol
  - K0ntol
  - k0ntol
  - K*ntol
  - k*ntol
  - K*nt*l
  - Tai
  - tai
  - t*i
  - ta1
  - Tai
  - T*i
  - Ta1
  - Asw
  - asw
  - asu
  - as*
  - as*
  - Asu
  - As*
  - Pepek
  - ngentot
  - Ngentot
  - tot
  - Tot
  - T0t
  - ToT
  - ngen
  - Ngen
  - entot
  - entot
  - anjing
  - ajg
  - Anjg
  - anjg
  - Anjing
  - Ajg
  - anj
  - Anj
  - stupid
  - Stupid
  - Ireng
  - ireng
  - tolol
  - Tolol
  - T0lol
  - t0lol
  - l0l
  - t0l0l
  - T0l0l
  - tololl
  - Tololl
  - gendut
  - Kurus
  - Gendut
  - kurus
  - babi
  - Babi
  - B4bi
  - bab1
  - Babiii
  - babii
  - dog
  - Dog
  - d0g
  - D0g
  - idiot